language: python
python:
    - "2.7"

install:
    - pip install git+https://github.com/travleev/Autologging.git
    - pip install .

script:
    - python tests/t_formula_to_tuple.py 
    - python tests/t_material.py


