''
This is arbitrary text, and this is 
a snippet: 'pi=3.14159', delimited 
with characters from the first line.
In this snippet, the variable pi is 
defined. After a variable is defined, 
it can be referenced: 'pi*2'.

A snippet can take several lines. It 
is like a python script, but saved 
directly in the template file. It can
access variables defined in previous
snippets. 
'
from math import cos
print
for x in [0, 0.3, 0.7, 1.]:
    print "%6f %9.2e" % (x, cos(pi*x))
'

The standard output generated by a 
snippet, if any, will be inserted 
into the resulting file right after
the snippet.
 
